DefaultContentLanguage = "fr"
baseURL = "https://blissful-sammet-2395f4.netlify.com"
languageCode = "fr"
title = "Vincent Guilleux"
theme = "ananke"

[params]
featured_image = "/images/coding_background.jpeg"
