DefaultContentLanguage = "fr"
baseURL = "https://vincentguilleux.netlify.app"
languageCode = "fr"
title = "Mes premiers pas dans le dev"
theme = "ananke"

[params]
featured_image = "/images/coding_background.jpeg"
author = "Vincent Guilleux"
description = "Blog Vincent Guilleux"
show_reading_time = true
