DefaultContentLanguage = "fr"
baseURL = "http://vincentguilleux.fr"
languageCode = "fr"
title = "Mes premiers pas dans le dev"
theme = "ananke"

[params]
featured_image = "/images/coding_background.jpeg"
